//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int classID { get; set; }
        public string className { get; set; }
        public string classNameEN { get; set; }
        public Nullable<int> ShopClassId { get; set; }
        public string classTip { get; set; }
        public string classUrl { get; set; }
        public string classRoles { get; set; }
        public Nullable<bool> classEnable { get; set; }
        public string classNameJP { get; set; }
    }
}
