//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XIMOStoreTestEntities : DbContext
    {
        public XIMOStoreTestEntities()
            : base("name=XIMOStoreTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityDetail> ActivityDetail { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BrandActivity> BrandActivity { get; set; }
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<DeliveryInformation> DeliveryInformation { get; set; }
        public virtual DbSet<DMsmallActivity> DMsmallActivity { get; set; }
        public virtual DbSet<GoodsNotice> GoodsNotice { get; set; }
        public virtual DbSet<LifeClass> LifeClass { get; set; }
        public virtual DbSet<LifeKowledge> LifeKowledge { get; set; }
        public virtual DbSet<LotteryList> LotteryList { get; set; }
        public virtual DbSet<ManageMenu> ManageMenu { get; set; }
        public virtual DbSet<ManageRole> ManageRole { get; set; }
        public virtual DbSet<ManageSubMenu> ManageSubMenu { get; set; }
        public virtual DbSet<MemberInfo> MemberInfo { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<OrderReplace> OrderReplace { get; set; }
        public virtual DbSet<PayType> PayType { get; set; }
        public virtual DbSet<ProCapacity> ProCapacity { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProPayType> ProPayType { get; set; }
        public virtual DbSet<ProState> ProState { get; set; }
        public virtual DbSet<RoleType> RoleType { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<ShopClass> ShopClass { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<VendorBrandList> VendorBrandList { get; set; }
        public virtual DbSet<VendorManage> VendorManage { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<WeekGift> WeekGift { get; set; }
        public virtual DbSet<WinPrize> WinPrize { get; set; }
    }
}
