//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeKowledge
    {
        public int LifeKowledgeId { get; set; }
        public string LifeTile { get; set; }
        public string LifeWord { get; set; }
        public string LifeTitleIMG { get; set; }
        public Nullable<int> LifeClassId { get; set; }
        public Nullable<System.DateTime> LifePostDate { get; set; }
        public string LifePostName { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> showOrder { get; set; }
        public string LifeContent { get; set; }
        public string RecommendTxt { get; set; }
        public Nullable<int> PID1 { get; set; }
        public Nullable<int> PID2 { get; set; }
        public Nullable<int> PID3 { get; set; }
        public Nullable<int> PID4 { get; set; }
        public string ProName1 { get; set; }
        public string ProName2 { get; set; }
        public string ProName3 { get; set; }
        public string ProName4 { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
