//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfo
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string cellphone { get; set; }
        public string sex { get; set; }
        public string postCode { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string personalNumber { get; set; }
        public Nullable<bool> memberShipState { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string Email { get; set; }
        public string name { get; set; }
        public string Introducer { get; set; }
        public string RoleName { get; set; }
        public string memo { get; set; }
    }
}
