//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public string UserName { get; set; }
        public string CusName { get; set; }
        public string CusEmail { get; set; }
        public Nullable<int> CusPostcode { get; set; }
        public string CusAddr { get; set; }
        public string CusPhone { get; set; }
        public string CusRemark { get; set; }
        public string Paytype { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string orderNote { get; set; }
        public string orderState { get; set; }
        public string payTime { get; set; }
        public string invoiceName { get; set; }
        public string invoiceNumber { get; set; }
        public string invoiceTitle { get; set; }
        public Nullable<bool> invoiceDonate { get; set; }
        public string UniformNumber { get; set; }
        public Nullable<bool> mailCheck { get; set; }
        public string FreeGift { get; set; }
        public string GuestIP { get; set; }
        public Nullable<System.DateTime> payCheckDate { get; set; }
        public string payCheckAccount { get; set; }
        public string orderRemark { get; set; }
        public string shipType { get; set; }
    }
}
