//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrdDtID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> CapacityID { get; set; }
        public string ProName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> OrdDetailAddTime { get; set; }
        public string UserName { get; set; }
        public string OEYACookie { get; set; }
        public string GoodsStatus { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryNumber { get; set; }
        public string VendorInvoiceNum { get; set; }
        public Nullable<bool> DeliveryMailCheck { get; set; }
        public Nullable<System.DateTime> DeliveryDateCreated_on { get; set; }
        public string DeliveryDateCreated_by { get; set; }
        public string DeliveryTypeRemark { get; set; }
    }
}
