//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProCapacity
    {
        public int CapacityID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public Nullable<int> classID { get; set; }
        public Nullable<int> ProStateID { get; set; }
        public string CapacityIMG { get; set; }
        public string CapacityBigIMG { get; set; }
        public string CapacityName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string pro_weight { get; set; }
        public string pro_length { get; set; }
        public string pro_height { get; set; }
        public Nullable<int> stockNumber { get; set; }
        public Nullable<int> lowStockNum { get; set; }
        public Nullable<int> maxBuyNum { get; set; }
        public string CartonSize { get; set; }
        public string EAN { get; set; }
    }
}
