//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PID { get; set; }
        public string ProName { get; set; }
        public string PronameEN { get; set; }
        public string ProCapacity { get; set; }
        public Nullable<decimal> price1 { get; set; }
        public Nullable<decimal> price2 { get; set; }
        public Nullable<decimal> price3 { get; set; }
        public Nullable<decimal> priceEmp { get; set; }
        public string description { get; set; }
        public string uses { get; set; }
        public string ingredients { get; set; }
        public string suitableUsers { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public string pic1 { get; set; }
        public string pic2 { get; set; }
        public string pic3 { get; set; }
        public string pic4 { get; set; }
        public string pic5 { get; set; }
        public string pic6 { get; set; }
        public string ProNote { get; set; }
        public string tureNumber { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_ip { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_ip { get; set; }
        public string ProNameAD { get; set; }
        public string ProNameAC { get; set; }
        public string proIMG1 { get; set; }
        public string proIMG2 { get; set; }
        public string proIMG3 { get; set; }
        public string proIMG4 { get; set; }
        public string ProContent { get; set; }
        public string ProContentEN { get; set; }
        public string ProVideo { get; set; }
        public string shipType { get; set; }
        public string priceCustomize { get; set; }
        public Nullable<decimal> extraprice { get; set; }
    }
}
