//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ximoShopping_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopClass
    {
        public int ShopClassId { get; set; }
        public string ShopClassName { get; set; }
        public string ShopClassNameS { get; set; }
        public string ShopClassNameEN { get; set; }
        public string ShopClassTip { get; set; }
        public string ShopClassUrl { get; set; }
        public string ShopClassRoles { get; set; }
        public Nullable<bool> ShopClassEnable { get; set; }
        public string ShopClassNameJP { get; set; }
        public string ShopClassNameSJP { get; set; }
        public string ShopClassTipJP { get; set; }
    }
}
